# Generated by Django 5.2.12 on 2026-07-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('deepfake_probability', models.FloatField(help_text='Percentage 0-100')),
                ('reconstruction_error', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_threshold', models.FloatField(default=0.15)),
                ('verdict', models.CharField(choices=[('AUTHENTIC', 'Authentic'), ('MANIPULATED', 'Manipulated')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('frame_crops_json', models.TextField(blank=True, help_text='JSON array of base64-encoded face crop thumbnails')),
                ('heatmaps_json', models.TextField(blank=True, help_text='JSON array of base64-encoded heatmap images')),
                ('processing_time', models.FloatField(help_text='Seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
